name: Deploy to production
on:
  release:
    types: [published]
    branches: main
jobs:
  deploy-production:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pegarobo"
          heroku_email: "nico@gruselhaus.com"
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Pegabot has been deployed.'
