name: Unit Tests
on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  test:
    name: "Running unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js "14.x"
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install --prefer-offline
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
        env:
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
  deploy:
    needs: test
    if: github.ref == 'refs/heads/staging'
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pegarobo-staging"
          heroku_email: "nico@gruselhaus.com"